apiVersion: v1
kind: Namespace
metadata:
  name: ns-proxy
spec:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-proxy
  namespace: ns-proxy
  labels:
    app: ns-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ns-proxy
  template:
    metadata:
      labels:
        app: ns-proxy
    spec:
      containers:
      - name: ns-proxy
        image: docker.io/danielkucera/ns-proxy:latest
        env:
          - name: TARGET_SERVICE
            value: changeme
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ns-proxy
  namespace: ns-proxy
spec:
  selector:
    app: ns-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ns-proxy
  namespace: ns-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - ns-proxy.changeme
  rules:
  - host: ns-proxy.changeme
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ns-proxy
            port:
              number: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ns-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

